version: '3.8'

services:
  mysql:
    image: mysql:latest
    ports:
      - "8002:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=Mypass123!
      - MYSQL_DATABASE=EmployeeDB
      - MYSQL_USER=adwait
      - MYSQL_PASSWORD=Mypass123!
    networks:
      - mynetwork
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./init_table.sql:/docker-entrypoint-initdb.d/init_table.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "adwait", "-pMypass123!"]
      interval: 10s
      timeout: 5s
      retries: 3

  webapi:
    image: my-first-image
    ports:
      - "50306:80"
    networks:
      - mynetwork
    depends_on:
      - mysql
    environment:
      - Database__Provider=MySql
      - Database__ConnectionString=server=database;database=EmployeeDB;uid=root;pwd=Mypass123!
  angularapp:
    image: my-second-image
    ports:
      - "4201:4200"
    networks:
      - mynetwork
    depends_on:
      - webapi

networks:
  mynetwork:
    driver: bridge

volumes:
  mysql_data:
